fix test compilation in release mode
in release mode, ppx_expect is stripped out and this fails to build
due to the value restriction:

```
File "test/test_scheduling.ml", line 870, characters 4-13:
870 | let pp_forget =
          ^^^^^^^^^
Error: The type of this expression,
       ('_weak1, [< `Still_connected | `Unknown_worker ] as '_weak2) result
       Fmt.t, contains the non-generalizable type variable(s): '_weak1,
       '_weak2. (see manual section 6.1.2)
```

An eta expansion suffices to fix it