Make dune build -p not require ppx_expect
```
$ dune build -p ocluster
File "test/dune", line 22, characters 19-29:
22 |   (preprocess (pps ppx_expect))
                        ^^^^^^^^^^
Error: Library "ppx_expect" not found.
```