Don't attach name_ocluster_expect_tests to a package
    File "test/dune", line 25, characters 4-6:
    25 |     db
             ^^
    Error: Library "db" is private, it cannot be a dependency of a private
    library attached to a package. You need to give "db" a public name.